### ISSUE TITLE
Failures in authentication should stop the worker

### ISSUE THREAD

**Issue by Fryguy** [ManageIQ/manageiq-providers-openshift#235]
With najdorf, I've run into 2 different errors where auth issues seem to just spin inside the worker instead of bringing down the worker (and validation failing)

1. I gave the provider a service account that did not have cluster:read, but it passed Validation.  The worker would then repeatedly give the following about once every 10 seconds:

```
[----] E, [2022-11-28T22:44:36.200368 #7:181c8]   ERR -- evm: /opt/manageiq/manageiq-gemset/gems/kubeclient-4.9.3/lib/kubeclient/watch_stream.rb:21:in `each'
/opt/manageiq/manageiq-gemset/bundler/gems/manageiq-providers-kubernetes-dd0c8d891812/app/models/manageiq/providers/kubernetes/container_manager/refresh_worker/watch_thread.rb:56:in `collector_thread'
/opt/manageiq/manageiq-gemset/bundler/gems/manageiq-providers-kubernetes-dd0c8d891812/app/models/manageiq/providers/kubernetes/container_manager/refresh_worker/watch_thread.rb:26:in `block in start!'
[----] E, [2022-11-28T22:44:36.207343 #7:18240]   ERR -- evm: [Kubeclient::HttpError]: Forbidden  Method:[block (2 levels) in <class:LogProxy>]
[----] E, [2022-11-28T22:44:36.210945 #7:1827c]   ERR -- evm: MIQ(ManageIQ::Providers::Openshift::ContainerManager::RefreshWorker::WatchThread#collector_thread) Watch thread for limit_ranges failed: HTTP status code 403, Forbidden
[----] E, [2022-11-28T22:44:36.214390 #7:18240]   ERR -- evm: /opt/manageiq/manageiq-gemset/gems/kubeclient-4.9.3/lib/kubeclient/watch_stream.rb:21:in `each'
/opt/manageiq/manageiq-gemset/bundler/gems/manageiq-providers-kubernetes-dd0c8d891812/app/models/manageiq/providers/kubernetes/container_manager/refresh_worker/watch_thread.rb:56:in `collector_thread'
/opt/manageiq/manageiq-gemset/bundler/gems/manageiq-providers-kubernetes-dd0c8d891812/app/models/manageiq/providers/kubernetes/container_manager/refresh_worker/watch_thread.rb:26:in `block in start!'
[----] E, [2022-11-28T22:44:36.216187 #7:1822c]   ERR -- evm: MIQ(ManageIQ::Providers::Openshift::ContainerManager::RefreshWorker::WatchThread#collector_thread) Watch thread for nodes failed: HTTP status code 403, Forbidden
[----] E, [2022-11-28T22:44:36.228804 #7:1827c]   ERR -- evm: [Kubeclient::HttpError]: Forbidden  Method:[block (2 levels) in <class:LogProxy>]
[----] E, [2022-11-28T22:44:36.235726 #7:18218]   ERR -- evm: [Kubeclient::HttpError]: Forbidden  Method:[block (2 levels) in <class:LogProxy>]
[----] E, [2022-11-28T22:44:36.219445 #7:18268]   ERR -- evm: MIQ(ManageIQ::Providers::Openshift::ContainerManager::RefreshWorker::WatchThread#collector_thread) Watch thread for resource_quotas failed: HTTP status code 403, Forbidden
[----] E, [2022-11-28T22:44:36.238352 #7:1822c]   ERR -- evm: [Kubeclient::HttpError]: Forbidden  Method:[block (2 levels) in <class:LogProxy>]
[----] E, [2022-11-28T22:44:36.220126 #7:181dc]   ERR -- evm: MIQ(ManageIQ::Providers::Openshift::ContainerManager::RefreshWorker::WatchThread#collector_thread) Watch thread for services failed: HTTP status code 403, Forbidden
[----] E, [2022-11-28T22:44:36.238725 #7:1827c]   ERR -- evm: /opt/manageiq/manageiq-gemset/gems/kubeclient-4.9.3/lib/kubeclient/watch_stream.rb:21:in `each'
/opt/manageiq/manageiq-gemset/bundler/gems/manageiq-providers-kubernetes-dd0c8d891812/app/models/manageiq/providers/kubernetes/container_manager/refresh_worker/watch_thread.rb:56:in `collector_thread'
/opt/manageiq/manageiq-gemset/bundler/gems/manageiq-providers-kubernetes-dd0c8d891812/app/models/manageiq/providers/kubernetes/container_manager/refresh_worker/watch_thread.rb:26:in `block in start!'
[----] E, [2022-11-28T22:44:36.218563 #7:181f0]   ERR -- evm: MIQ(ManageIQ::Providers::Openshift::ContainerManager::RefreshWorker::WatchThread#collector_thread) Watch thread for endpoints failed: HTTP status code 403, Forbidden
[----] E, [2022-11-28T22:44:36.222002 #7:182a4]   ERR -- evm: MIQ(ManageIQ::Providers::Openshift::ContainerManager::RefreshWorker::WatchThread#collector_thread) Watch thread for persistent_volumes failed: HTTP status code 403, Forbidden
[----] E, [2022-11-28T22:44:36.240127 #7:182e0]   ERR -- evm: MIQ(ManageIQ::Providers::Openshift::ContainerManager::RefreshWorker::WatchThread#collector_thread) Watch thread for build_configs failed: HTTP status code 403, Forbidden
[----] E, [2022-11-28T22:44:36.219077 #7:182b8]   ERR -- evm: MIQ(ManageIQ::Providers::Openshift::ContainerManager::RefreshWorker::WatchThread#collector_thread) Watch thread for persistent_volume_claims failed: HTTP status code 403, Forbidden
[----] E, [2022-11-28T22:44:36.242554 #7:182b8]   ERR -- evm: [Kubeclient::HttpError]: Forbidden  Method:[block (2 levels) in <class:LogProxy>]
[----] E, [2022-11-28T22:44:36.243877 #7:18308]   ERR -- evm: MIQ(ManageIQ::Providers::Openshift::ContainerManager::RefreshWorker::WatchThread#collector_thread) Watch thread for builds failed: HTTP status code 403, Forbidden
[----] E, [2022-11-28T22:44:36.244023 #7:181dc]   ERR -- evm: [Kubeclient::HttpError]: Forbidden  Method:[block (2 levels) in <class:LogProxy>]
[----] E, [2022-11-28T22:44:36.239149 #7:181f0]   ERR -- evm: [Kubeclient::HttpError]: Forbidden  Method:[block (2 levels) in <class:LogProxy>]
[----] E, [2022-11-28T22:44:36.243098 #7:1831c]   ERR -- evm: MIQ(ManageIQ::Providers::Openshift::ContainerManager::RefreshWorker::WatchThread#collector_thread) Watch thread for templates failed: HTTP status code 403, Forbidden
[----] E, [2022-11-28T22:44:36.240283 #7:182a4]   ERR -- evm: [Kubeclient::HttpError]: Forbidden  Method:[block (2 levels) in <class:LogProxy>]
[----] E, [2022-11-28T22:44:36.244501 #7:181f0]   ERR -- evm: /opt/manageiq/manageiq-gemset/gems/kubeclient-4.9.3/lib/kubeclient/watch_stream.rb:21:in `each'
/opt/manageiq/manageiq-gemset/bundler/gems/manageiq-providers-kubernetes-dd0c8d891812/app/models/manageiq/providers/kubernetes/container_manager/refresh_worker/watch_thread.rb:56:in `collector_thread'
/opt/manageiq/manageiq-gemset/bundler/gems/manageiq-providers-kubernetes-dd0c8d891812/app/models/manageiq/providers/kubernetes/container_manager/refresh_worker/watch_thread.rb:26:in `block in start!'
[----] E, [2022-11-28T22:44:36.243423 #7:182cc]   ERR -- evm: MIQ(ManageIQ::Providers::Openshift::ContainerManager::RefreshWorker::WatchThread#collector_thread) Watch thread for routes failed: HTTP status code 403, Forbidden
[----] E, [2022-11-28T22:44:36.244751 #7:182cc]   ERR -- evm: [Kubeclient::HttpError]: Forbidden  Method:[block (2 levels) in <class:LogProxy>]
[----] E, [2022-11-28T22:44:36.245077 #7:182cc]   ERR -- evm: /opt/manageiq/manageiq-gemset/gems/kubeclient-4.9.3/lib/kubeclient/watch_stream.rb:21:in `each'
/opt/manageiq/manageiq-gemset/bundler/gems/manageiq-providers-kubernetes-dd0c8d891812/app/models/manageiq/providers/kubernetes/container_manager/refresh_worker/watch_thread.rb:56:in `collector_thread'
/opt/manageiq/manageiq-gemset/bundler/gems/manageiq-providers-kubernetes-dd0c8d891812/app/models/manageiq/providers/kubernetes/container_manager/refresh_worker/watch_thread.rb:26:in `block in start!'
[----] E, [2022-11-28T22:44:36.244982 #7:18268]   ERR -- evm: [Kubeclient::HttpError]: Forbidden  Method:[block (2 levels) in <class:LogProxy>]
[----] E, [2022-11-28T22:44:36.245252 #7:18308]   ERR -- evm: [Kubeclient::HttpError]: Forbidden  Method:[block (2 levels) in <class:LogProxy>]
[----] E, [2022-11-28T22:44:36.245453 #7:1831c]   ERR -- evm: [Kubeclient::HttpError]: Forbidden  Method:[block (2 levels) in <class:LogProxy>]
[----] E, [2022-11-28T22:44:36.245948 #7:182a4]   ERR -- evm: /opt/manageiq/manageiq-gemset/gems/kubeclient-4.9.3/lib/kubeclient/watch_stream.rb:21:in `each'
/opt/manageiq/manageiq-gemset/bundler/gems/manageiq-providers-kubernetes-dd0c8d891812/app/models/manageiq/providers/kubernetes/container_manager/refresh_worker/watch_thread.rb:56:in `collector_thread'
/opt/manageiq/manageiq-gemset/bundler/gems/manageiq-providers-kubernetes-dd0c8d891812/app/models/manageiq/providers/kubernetes/container_manager/refresh_worker/watch_thread.rb:26:in `block in start!'
```

2. I fixed the creds, but then the workers did not restart, likely because it was "already validated".  I'm wondering if a re-validation should somehow bounce the workers anyway?  Not sure here.

3. Now having what I thought was good creds, I added the prometheus endpoint and it validated successfully.  However, I get the following errors repeatedly without pause (I guess once per image on the queue?)

```
[----] I, [2022-11-28T22:54:33.098656 #7:9830]  INFO -- evm: MIQ(MiqQueue#deliver) Message id: [2006627], Delivering...
[----] I, [2022-11-28T22:54:33.100151 #7:9830]  INFO -- evm: MIQ(ManageIQ::Providers::Openshift::ContainerManager::ContainerImage#just_perf_capture) [realtime] Capture for ManageIQ::Providers::Openshift::ContainerManager::ContainerImage name: [3scale-amp2/apicast-gateway-rhel8], id: [536], start_time: [2022-11-28 00:00:00 UTC]...
[----] I, [2022-11-28T22:54:33.114208 #7:9830]  INFO -- evm: MIQ(ManageIQ::Providers::Kubernetes::ContainerManager::MetricsCapture#perf_collect_metrics) Collecting metrics for ContainerImage(536) [realtime] [2022-11-28 00:00:00 UTC] []
[----] W, [2022-11-28T22:54:33.117382 #7:9830] WARNI -- evm: MIQ(ManageIQ::Providers::Kubernetes::ContainerManager::MetricsCapture#perf_collect_metrics) [ContainerImage(536)] metrics authentication isn't valid for ContainerImage(536)
[----] E, [2022-11-28T22:54:33.133628 #7:9830]   ERR -- evm: MIQ(MiqQueue#deliver) Message id: [2006627], Error: [metrics authentication isn't valid for ContainerImage(536)]
[----] E, [2022-11-28T22:54:33.133864 #7:9830]   ERR -- evm: [ManageIQ::Providers::Kubernetes::ContainerManager::MetricsCapture::TargetValidationWarning]: metrics authentication isn't valid for ContainerImage(536)  Method:[block (2 levels) in <class:LogProxy>]
[----] E, [2022-11-28T22:54:33.133948 #7:9830]   ERR -- evm: /opt/manageiq/manageiq-gemset/bundler/gems/manageiq-providers-kubernetes-dd0c8d891812/app/models/manageiq/providers/kubernetes/container_manager/metrics_capture.rb:80:in `perf_collect_metrics'
/var/www/miq/vmdb/app/models/metric/ci_mixin/capture.rb:10:in `perf_collect_metrics'
/var/www/miq/vmdb/app/models/metric/ci_mixin/capture.rb:92:in `block in just_perf_capture'
/opt/manageiq/manageiq-gemset/gems/more_core_extensions-4.4.0/lib/more_core_extensions/core_ext/benchmark/realtime_store.rb:20:in `realtime_store'
/opt/manageiq/manageiq-gemset/gems/more_core_extensions-4.4.0/lib/more_core_extensions/core_ext/benchmark/realtime_store.rb:62:in `realtime_block'
/var/www/miq/vmdb/app/models/metric/ci_mixin/capture.rb:88:in `just_perf_capture'
/var/www/miq/vmdb/app/models/metric/ci_mixin/capture.rb:37:in `perf_capture'
/var/www/miq/vmdb/app/models/metric/ci_mixin/capture.rb:13:in `perf_capture_realtime'
/var/www/miq/vmdb/app/models/miq_queue.rb:484:in `block in dispatch_method'
/usr/share/ruby/timeout.rb:95:in `block in timeout'
/usr/share/ruby/timeout.rb:33:in `block in catch'
/usr/share/ruby/timeout.rb:33:in `catch'
/usr/share/ruby/timeout.rb:33:in `catch'
/usr/share/ruby/timeout.rb:110:in `timeout'
/var/www/miq/vmdb/app/models/miq_queue.rb:482:in `dispatch_method'
/var/www/miq/vmdb/app/models/miq_queue.rb:459:in `block in deliver'
/var/www/miq/vmdb/app/models/user.rb:382:in `with_user_group'
/var/www/miq/vmdb/app/models/miq_queue.rb:459:in `deliver'
/var/www/miq/vmdb/app/models/miq_queue_worker_base/runner.rb:98:in `deliver_queue_message'
/var/www/miq/vmdb/app/models/miq_queue_worker_base/runner.rb:124:in `deliver_message'
/var/www/miq/vmdb/app/models/miq_queue_worker_base/runner.rb:146:in `block in do_work'
/var/www/miq/vmdb/app/models/miq_queue_worker_base/runner.rb:142:in `loop'
/var/www/miq/vmdb/app/models/miq_queue_worker_base/runner.rb:142:in `do_work'
/var/www/miq/vmdb/app/models/miq_worker/runner.rb:267:in `block in do_work_loop'
/var/www/miq/vmdb/app/models/miq_worker/runner.rb:264:in `loop'
/var/www/miq/vmdb/app/models/miq_worker/runner.rb:264:in `do_work_loop'
/var/www/miq/vmdb/app/models/miq_worker/runner.rb:114:in `run'
/var/www/miq/vmdb/app/models/miq_worker/runner.rb:96:in `start'
/var/www/miq/vmdb/lib/workers/bin/run_single_worker.rb:128:in `<main>'
[----] I, [2022-11-28T22:54:33.134065 #7:9830]  INFO -- evm: MIQ(MiqQueue#delivered) Message id: [2006627], State: [error], Delivered in [0.035419803] seconds
[----] I, [2022-11-28T22:54:33.150017 #7:9830]  INFO -- evm: MIQ(MiqQueue.get) Message id: [2006629], Zone: [default], Role: [ems_metrics_collector], Server: [], MiqTask id: [], Handler id: [MiqWorker 268], Ident: [openshift], Target id: [], Instance id: [540], Task id: [], Command: [ManageIQ::Providers::Openshift::ContainerManager::ContainerImage.perf_capture_realtime], Timeout: [600], Priority: [100], State: [dequeue], Deliver On: [], Data: [], Args: [], Dequeued in: [64.746215908] seconds
```

**Comment by agrare** [comment]
The metrics capture worker at least is due to overriding the wrong method to check for valid EMSs in the zone: https://github.com/ManageIQ/manageiq-providers-kubernetes/pull/476

**Comment by agrare** [comment]
The issue with the RefreshWorker is that the authentication is actually valid according to the `verify_credentials` method so it was not marked invalid.  This is fixed by https://github.com/ManageIQ/manageiq-providers-kubernetes/pull/478

**Comment by agrare** [comment]
> I fixed the creds, but then the workers did not restart, likely because it was "already validated". 

For workers which do streaming refresh I think we need to restart on auth changes like we do with Event Catchers, I'll look into doing this generically in core checking the `streaming_refresh` setting

**Comment by agrare** [comment]
> I fixed the creds, but then the workers did not restart, likely because it was "already validated".

Actually I found we already do stop the refresh worker on credential change for exactly this reason, going to test to see if this still works as expected

**Comment by Fryguy** [comment]
@agrare Is this still an issue?

**Comment by agrare** [comment]
No I wasn't able to reproduce this it we can close it
